[package]
name = "appstore"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "appstore"
crate-type = ["cdylib", "rlib"]

[dependencies]
appstore_types = {path = "../../appstore_types"}
essence_payloads = "0.1"
hc_crud_caps = "0.5.0"
hc_utils = {path = "../../hc_utils"}
hdi = "0.3.0-beta-rc.3"
hdk = "0.2.0-beta-rc.4"
mere_memory_types = "0.83.0"
serde = "1"
serde_yaml = "0.8.17"
thiserror = "1"
