[package]
name = "appstore"
version = "0.0.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "appstore"
crate-type = ["cdylib", "rlib"]

[dependencies]
appstore_types = {path = "../../dnas/appstore/types"}
hc_crud_caps = "0.10.3"
mere_memory_types = "0.91.0"
serde = "1"
whi_hdi_extensions = "0.4.2"
