[package]
name = "hc_utils"
version = "0.3.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hc_utils"
crate-type = ["cdylib", "rlib"]

[dependencies]
essence_payloads = "0.1"
hc_crud_caps = { git = "https://github.com/mjbrisebois/rust-hc-crud-caps.git", rev = "10d042c36024e2d839008bdb621595a8c09f0b74" }
hdi = "0.2.3-beta-rc.0"
hdk = "0.1.3-beta-rc.1"
serde = "1"
serde_yaml = "0.8.17"
thiserror = "1"
